- name: Creates directory
  file:
    path: ~/backend_dir
    state: directory

- name: Copy folder to host
  copy:
    src: ~/project/backend
    dest: ~/backend_dir 

- name: Executing node
  shell: |
    cd ~/backend_dir/backend
    npm install
    npm run build
    pm2 start npm -- start
- name: Sleep 10s to wait server before smoke-test
  ansible.builtin.pause:
    seconds: 10